// <auto-generated />
using System;
using GIsDataWorker.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GIsDataWorker.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GIsDataWorker.Models.osm2pgsql_property", b =>
                {
                    b.Property<string>("property")
                        .HasColumnType("text")
                        .HasColumnName("property");

                    b.Property<string>("value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("property")
                        .HasName("osm2pgsql_properties_pkey");

                    b.ToTable("osm2pgsql_properties", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("GIsDataWorker.Models.planet_osm_line", b =>
                {
                    b.Property<string>("_lock")
                        .HasColumnType("text")
                        .HasColumnName("lock");

                    b.Property<string>("_operator")
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<string>("_ref")
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<string>("access")
                        .HasColumnType("text");

                    b.Property<string>("addr_housename")
                        .HasColumnType("text")
                        .HasColumnName("addr:housename");

                    b.Property<string>("addr_housenumber")
                        .HasColumnType("text")
                        .HasColumnName("addr:housenumber");

                    b.Property<string>("addr_interpolation")
                        .HasColumnType("text")
                        .HasColumnName("addr:interpolation");

                    b.Property<string>("admin_level")
                        .HasColumnType("text");

                    b.Property<string>("aerialway")
                        .HasColumnType("text");

                    b.Property<string>("aeroway")
                        .HasColumnType("text");

                    b.Property<string>("amenity")
                        .HasColumnType("text");

                    b.Property<string>("area")
                        .HasColumnType("text");

                    b.Property<string>("barrier")
                        .HasColumnType("text");

                    b.Property<string>("bicycle")
                        .HasColumnType("text");

                    b.Property<string>("boundary")
                        .HasColumnType("text");

                    b.Property<string>("brand")
                        .HasColumnType("text");

                    b.Property<string>("bridge")
                        .HasColumnType("text");

                    b.Property<string>("building")
                        .HasColumnType("text");

                    b.Property<string>("construction")
                        .HasColumnType("text");

                    b.Property<string>("covered")
                        .HasColumnType("text");

                    b.Property<string>("culvert")
                        .HasColumnType("text");

                    b.Property<string>("cutting")
                        .HasColumnType("text");

                    b.Property<string>("denomination")
                        .HasColumnType("text");

                    b.Property<string>("disused")
                        .HasColumnType("text");

                    b.Property<string>("embankment")
                        .HasColumnType("text");

                    b.Property<string>("foot")
                        .HasColumnType("text");

                    b.Property<string>("generator_source")
                        .HasColumnType("text")
                        .HasColumnName("generator:source");

                    b.Property<string>("harbour")
                        .HasColumnType("text");

                    b.Property<string>("highway")
                        .HasColumnType("text");

                    b.Property<string>("historic")
                        .HasColumnType("text");

                    b.Property<string>("horse")
                        .HasColumnType("text");

                    b.Property<string>("intermittent")
                        .HasColumnType("text");

                    b.Property<string>("junction")
                        .HasColumnType("text");

                    b.Property<string>("landuse")
                        .HasColumnType("text");

                    b.Property<string>("layer")
                        .HasColumnType("text");

                    b.Property<string>("leisure")
                        .HasColumnType("text");

                    b.Property<string>("man_made")
                        .HasColumnType("text");

                    b.Property<string>("military")
                        .HasColumnType("text");

                    b.Property<string>("motorcar")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("natural")
                        .HasColumnType("text")
                        .HasColumnName("natural");

                    b.Property<string>("office")
                        .HasColumnType("text");

                    b.Property<string>("oneway")
                        .HasColumnType("text");

                    b.Property<long?>("osm_id")
                        .HasColumnType("bigint");

                    b.Property<string>("place")
                        .HasColumnType("text");

                    b.Property<string>("population")
                        .HasColumnType("text");

                    b.Property<string>("power")
                        .HasColumnType("text");

                    b.Property<string>("power_source")
                        .HasColumnType("text");

                    b.Property<string>("public_transport")
                        .HasColumnType("text");

                    b.Property<string>("railway")
                        .HasColumnType("text");

                    b.Property<string>("religion")
                        .HasColumnType("text");

                    b.Property<string>("route")
                        .HasColumnType("text");

                    b.Property<string>("service")
                        .HasColumnType("text");

                    b.Property<string>("shop")
                        .HasColumnType("text");

                    b.Property<string>("sport")
                        .HasColumnType("text");

                    b.Property<string>("surface")
                        .HasColumnType("text");

                    b.Property<string>("toll")
                        .HasColumnType("text");

                    b.Property<string>("tourism")
                        .HasColumnType("text");

                    b.Property<string>("tower_type")
                        .HasColumnType("text")
                        .HasColumnName("tower:type");

                    b.Property<string>("tracktype")
                        .HasColumnType("text");

                    b.Property<string>("tunnel")
                        .HasColumnType("text");

                    b.Property<string>("water")
                        .HasColumnType("text");

                    b.Property<string>("waterway")
                        .HasColumnType("text");

                    b.Property<LineString>("way")
                        .HasColumnType("geometry(LineString,3857)");

                    b.Property<float?>("way_area")
                        .HasColumnType("real");

                    b.Property<string>("wetland")
                        .HasColumnType("text");

                    b.Property<string>("width")
                        .HasColumnType("text");

                    b.Property<string>("wood")
                        .HasColumnType("text");

                    b.Property<int?>("z_order")
                        .HasColumnType("integer");

                    b.HasIndex(new[] { "osm_id" }, "planet_osm_line_osm_id_idx");

                    b.HasIndex(new[] { "way" }, "planet_osm_line_way_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "way" }, "planet_osm_line_way_idx"), "gist");

                    b.ToTable("planet_osm_line", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("GIsDataWorker.Models.planet_osm_node", b =>
                {
                    b.Property<long>("id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<int>("lat")
                        .HasColumnType("integer")
                        .HasColumnName("lat");

                    b.Property<int>("lon")
                        .HasColumnType("integer")
                        .HasColumnName("lon");

                    b.Property<string>("tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.HasKey("id")
                        .HasName("planet_osm_nodes_pkey");

                    b.ToTable("planet_osm_nodes", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("GIsDataWorker.Models.planet_osm_point", b =>
                {
                    b.Property<string>("_lock")
                        .HasColumnType("text")
                        .HasColumnName("lock");

                    b.Property<string>("_operator")
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<string>("_ref")
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<string>("access")
                        .HasColumnType("text");

                    b.Property<string>("addr_housename")
                        .HasColumnType("text")
                        .HasColumnName("addr:housename");

                    b.Property<string>("addr_housenumber")
                        .HasColumnType("text")
                        .HasColumnName("addr:housenumber");

                    b.Property<string>("addr_interpolation")
                        .HasColumnType("text")
                        .HasColumnName("addr:interpolation");

                    b.Property<string>("admin_level")
                        .HasColumnType("text");

                    b.Property<string>("aerialway")
                        .HasColumnType("text");

                    b.Property<string>("aeroway")
                        .HasColumnType("text");

                    b.Property<string>("amenity")
                        .HasColumnType("text");

                    b.Property<string>("area")
                        .HasColumnType("text");

                    b.Property<string>("barrier")
                        .HasColumnType("text");

                    b.Property<string>("bicycle")
                        .HasColumnType("text");

                    b.Property<string>("boundary")
                        .HasColumnType("text");

                    b.Property<string>("brand")
                        .HasColumnType("text");

                    b.Property<string>("bridge")
                        .HasColumnType("text");

                    b.Property<string>("building")
                        .HasColumnType("text");

                    b.Property<string>("capital")
                        .HasColumnType("text");

                    b.Property<string>("construction")
                        .HasColumnType("text");

                    b.Property<string>("covered")
                        .HasColumnType("text");

                    b.Property<string>("culvert")
                        .HasColumnType("text");

                    b.Property<string>("cutting")
                        .HasColumnType("text");

                    b.Property<string>("denomination")
                        .HasColumnType("text");

                    b.Property<string>("disused")
                        .HasColumnType("text");

                    b.Property<string>("ele")
                        .HasColumnType("text");

                    b.Property<string>("embankment")
                        .HasColumnType("text");

                    b.Property<string>("foot")
                        .HasColumnType("text");

                    b.Property<string>("generator_source")
                        .HasColumnType("text")
                        .HasColumnName("generator:source");

                    b.Property<string>("harbour")
                        .HasColumnType("text");

                    b.Property<string>("highway")
                        .HasColumnType("text");

                    b.Property<string>("historic")
                        .HasColumnType("text");

                    b.Property<string>("horse")
                        .HasColumnType("text");

                    b.Property<string>("intermittent")
                        .HasColumnType("text");

                    b.Property<string>("junction")
                        .HasColumnType("text");

                    b.Property<string>("landuse")
                        .HasColumnType("text");

                    b.Property<string>("layer")
                        .HasColumnType("text");

                    b.Property<string>("leisure")
                        .HasColumnType("text");

                    b.Property<string>("man_made")
                        .HasColumnType("text");

                    b.Property<string>("military")
                        .HasColumnType("text");

                    b.Property<string>("motorcar")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("natural")
                        .HasColumnType("text")
                        .HasColumnName("natural");

                    b.Property<string>("office")
                        .HasColumnType("text");

                    b.Property<string>("oneway")
                        .HasColumnType("text");

                    b.Property<long?>("osm_id")
                        .HasColumnType("bigint");

                    b.Property<string>("place")
                        .HasColumnType("text");

                    b.Property<string>("population")
                        .HasColumnType("text");

                    b.Property<string>("power")
                        .HasColumnType("text");

                    b.Property<string>("power_source")
                        .HasColumnType("text");

                    b.Property<string>("public_transport")
                        .HasColumnType("text");

                    b.Property<string>("railway")
                        .HasColumnType("text");

                    b.Property<string>("religion")
                        .HasColumnType("text");

                    b.Property<string>("route")
                        .HasColumnType("text");

                    b.Property<string>("service")
                        .HasColumnType("text");

                    b.Property<string>("shop")
                        .HasColumnType("text");

                    b.Property<string>("sport")
                        .HasColumnType("text");

                    b.Property<string>("surface")
                        .HasColumnType("text");

                    b.Property<string>("toll")
                        .HasColumnType("text");

                    b.Property<string>("tourism")
                        .HasColumnType("text");

                    b.Property<string>("tower_type")
                        .HasColumnType("text")
                        .HasColumnName("tower:type");

                    b.Property<string>("tunnel")
                        .HasColumnType("text");

                    b.Property<string>("water")
                        .HasColumnType("text");

                    b.Property<string>("waterway")
                        .HasColumnType("text");

                    b.Property<Point>("way")
                        .HasColumnType("geometry(Point,3857)")
                        .HasColumnName("way");

                    b.Property<string>("wetland")
                        .HasColumnType("text");

                    b.Property<string>("width")
                        .HasColumnType("text");

                    b.Property<string>("wood")
                        .HasColumnType("text");

                    b.Property<int?>("z_order")
                        .HasColumnType("integer");

                    b.HasIndex(new[] { "osm_id" }, "planet_osm_point_osm_id_idx");

                    b.HasIndex(new[] { "way" }, "planet_osm_point_way_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "way" }, "planet_osm_point_way_idx"), "gist");

                    b.ToTable("planet_osm_point", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("GIsDataWorker.Models.planet_osm_polygon", b =>
                {
                    b.Property<string>("_lock")
                        .HasColumnType("text")
                        .HasColumnName("lock");

                    b.Property<string>("_operator")
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<string>("_ref")
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<string>("access")
                        .HasColumnType("text");

                    b.Property<string>("addr_housename")
                        .HasColumnType("text")
                        .HasColumnName("addr:housename");

                    b.Property<string>("addr_housenumber")
                        .HasColumnType("text")
                        .HasColumnName("addr:housenumber");

                    b.Property<string>("addr_interpolation")
                        .HasColumnType("text")
                        .HasColumnName("addr:interpolation");

                    b.Property<string>("admin_level")
                        .HasColumnType("text");

                    b.Property<string>("aerialway")
                        .HasColumnType("text");

                    b.Property<string>("aeroway")
                        .HasColumnType("text");

                    b.Property<string>("amenity")
                        .HasColumnType("text");

                    b.Property<string>("area")
                        .HasColumnType("text");

                    b.Property<string>("barrier")
                        .HasColumnType("text");

                    b.Property<string>("bicycle")
                        .HasColumnType("text");

                    b.Property<string>("boundary")
                        .HasColumnType("text");

                    b.Property<string>("brand")
                        .HasColumnType("text");

                    b.Property<string>("bridge")
                        .HasColumnType("text");

                    b.Property<string>("building")
                        .HasColumnType("text");

                    b.Property<string>("construction")
                        .HasColumnType("text");

                    b.Property<string>("covered")
                        .HasColumnType("text");

                    b.Property<string>("culvert")
                        .HasColumnType("text");

                    b.Property<string>("cutting")
                        .HasColumnType("text");

                    b.Property<string>("denomination")
                        .HasColumnType("text");

                    b.Property<string>("disused")
                        .HasColumnType("text");

                    b.Property<string>("embankment")
                        .HasColumnType("text");

                    b.Property<string>("foot")
                        .HasColumnType("text");

                    b.Property<string>("generator_source")
                        .HasColumnType("text")
                        .HasColumnName("generator:source");

                    b.Property<string>("harbour")
                        .HasColumnType("text");

                    b.Property<string>("highway")
                        .HasColumnType("text");

                    b.Property<string>("historic")
                        .HasColumnType("text");

                    b.Property<string>("horse")
                        .HasColumnType("text");

                    b.Property<string>("intermittent")
                        .HasColumnType("text");

                    b.Property<string>("junction")
                        .HasColumnType("text");

                    b.Property<string>("landuse")
                        .HasColumnType("text");

                    b.Property<string>("layer")
                        .HasColumnType("text");

                    b.Property<string>("leisure")
                        .HasColumnType("text");

                    b.Property<string>("man_made")
                        .HasColumnType("text");

                    b.Property<string>("military")
                        .HasColumnType("text");

                    b.Property<string>("motorcar")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("natural")
                        .HasColumnType("text")
                        .HasColumnName("natural");

                    b.Property<string>("office")
                        .HasColumnType("text");

                    b.Property<string>("oneway")
                        .HasColumnType("text");

                    b.Property<long?>("osm_id")
                        .HasColumnType("bigint");

                    b.Property<string>("place")
                        .HasColumnType("text");

                    b.Property<string>("population")
                        .HasColumnType("text");

                    b.Property<string>("power")
                        .HasColumnType("text");

                    b.Property<string>("power_source")
                        .HasColumnType("text");

                    b.Property<string>("public_transport")
                        .HasColumnType("text");

                    b.Property<string>("railway")
                        .HasColumnType("text");

                    b.Property<string>("religion")
                        .HasColumnType("text");

                    b.Property<string>("route")
                        .HasColumnType("text");

                    b.Property<string>("service")
                        .HasColumnType("text");

                    b.Property<string>("shop")
                        .HasColumnType("text");

                    b.Property<string>("sport")
                        .HasColumnType("text");

                    b.Property<string>("surface")
                        .HasColumnType("text");

                    b.Property<string>("toll")
                        .HasColumnType("text");

                    b.Property<string>("tourism")
                        .HasColumnType("text");

                    b.Property<string>("tower_type")
                        .HasColumnType("text")
                        .HasColumnName("tower:type");

                    b.Property<string>("tracktype")
                        .HasColumnType("text");

                    b.Property<string>("tunnel")
                        .HasColumnType("text");

                    b.Property<string>("water")
                        .HasColumnType("text");

                    b.Property<string>("waterway")
                        .HasColumnType("text");

                    b.Property<Geometry>("way")
                        .HasColumnType("geometry(Geometry,3857)")
                        .HasColumnName("way");

                    b.Property<float?>("way_area")
                        .HasColumnType("real");

                    b.Property<string>("wetland")
                        .HasColumnType("text");

                    b.Property<string>("width")
                        .HasColumnType("text");

                    b.Property<string>("wood")
                        .HasColumnType("text");

                    b.Property<int?>("z_order")
                        .HasColumnType("integer");

                    b.HasIndex(new[] { "osm_id" }, "planet_osm_polygon_osm_id_idx");

                    b.HasIndex(new[] { "way" }, "planet_osm_polygon_way_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "way" }, "planet_osm_polygon_way_idx"), "gist");

                    b.ToTable("planet_osm_polygon", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("GIsDataWorker.Models.planet_osm_rel", b =>
                {
                    b.Property<long>("id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("members")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("members");

                    b.Property<string>("tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.HasKey("id")
                        .HasName("planet_osm_rels_pkey");

                    b.ToTable("planet_osm_rels", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("GIsDataWorker.Models.planet_osm_road", b =>
                {
                    b.Property<string>("_lock")
                        .HasColumnType("text")
                        .HasColumnName("lock");

                    b.Property<string>("_operator")
                        .HasColumnType("text")
                        .HasColumnName("operator");

                    b.Property<string>("_ref")
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<string>("access")
                        .HasColumnType("text");

                    b.Property<string>("addr_housename")
                        .HasColumnType("text")
                        .HasColumnName("addr:housename");

                    b.Property<string>("addr_housenumber")
                        .HasColumnType("text")
                        .HasColumnName("addr:housenumber");

                    b.Property<string>("addr_interpolation")
                        .HasColumnType("text")
                        .HasColumnName("addr:interpolation");

                    b.Property<string>("admin_level")
                        .HasColumnType("text");

                    b.Property<string>("aerialway")
                        .HasColumnType("text");

                    b.Property<string>("aeroway")
                        .HasColumnType("text");

                    b.Property<string>("amenity")
                        .HasColumnType("text");

                    b.Property<string>("area")
                        .HasColumnType("text");

                    b.Property<string>("barrier")
                        .HasColumnType("text");

                    b.Property<string>("bicycle")
                        .HasColumnType("text");

                    b.Property<string>("boundary")
                        .HasColumnType("text");

                    b.Property<string>("brand")
                        .HasColumnType("text");

                    b.Property<string>("bridge")
                        .HasColumnType("text");

                    b.Property<string>("building")
                        .HasColumnType("text");

                    b.Property<string>("construction")
                        .HasColumnType("text");

                    b.Property<string>("covered")
                        .HasColumnType("text");

                    b.Property<string>("culvert")
                        .HasColumnType("text");

                    b.Property<string>("cutting")
                        .HasColumnType("text");

                    b.Property<string>("denomination")
                        .HasColumnType("text");

                    b.Property<string>("disused")
                        .HasColumnType("text");

                    b.Property<string>("embankment")
                        .HasColumnType("text");

                    b.Property<string>("foot")
                        .HasColumnType("text");

                    b.Property<string>("generator_source")
                        .HasColumnType("text")
                        .HasColumnName("generator:source");

                    b.Property<string>("harbour")
                        .HasColumnType("text");

                    b.Property<string>("highway")
                        .HasColumnType("text");

                    b.Property<string>("historic")
                        .HasColumnType("text");

                    b.Property<string>("horse")
                        .HasColumnType("text");

                    b.Property<string>("intermittent")
                        .HasColumnType("text");

                    b.Property<string>("junction")
                        .HasColumnType("text");

                    b.Property<string>("landuse")
                        .HasColumnType("text");

                    b.Property<string>("layer")
                        .HasColumnType("text");

                    b.Property<string>("leisure")
                        .HasColumnType("text");

                    b.Property<string>("man_made")
                        .HasColumnType("text");

                    b.Property<string>("military")
                        .HasColumnType("text");

                    b.Property<string>("motorcar")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .HasColumnType("text");

                    b.Property<string>("natural")
                        .HasColumnType("text")
                        .HasColumnName("natural");

                    b.Property<string>("office")
                        .HasColumnType("text");

                    b.Property<string>("oneway")
                        .HasColumnType("text");

                    b.Property<long?>("osm_id")
                        .HasColumnType("bigint");

                    b.Property<string>("place")
                        .HasColumnType("text");

                    b.Property<string>("population")
                        .HasColumnType("text");

                    b.Property<string>("power")
                        .HasColumnType("text");

                    b.Property<string>("power_source")
                        .HasColumnType("text");

                    b.Property<string>("public_transport")
                        .HasColumnType("text");

                    b.Property<string>("railway")
                        .HasColumnType("text");

                    b.Property<string>("religion")
                        .HasColumnType("text");

                    b.Property<string>("route")
                        .HasColumnType("text");

                    b.Property<string>("service")
                        .HasColumnType("text");

                    b.Property<string>("shop")
                        .HasColumnType("text");

                    b.Property<string>("sport")
                        .HasColumnType("text");

                    b.Property<string>("surface")
                        .HasColumnType("text");

                    b.Property<string>("toll")
                        .HasColumnType("text");

                    b.Property<string>("tourism")
                        .HasColumnType("text");

                    b.Property<string>("tower_type")
                        .HasColumnType("text")
                        .HasColumnName("tower:type");

                    b.Property<string>("tracktype")
                        .HasColumnType("text");

                    b.Property<string>("tunnel")
                        .HasColumnType("text");

                    b.Property<string>("water")
                        .HasColumnType("text");

                    b.Property<string>("waterway")
                        .HasColumnType("text");

                    b.Property<LineString>("way")
                        .HasColumnType("geometry(LineString,3857)")
                        .HasColumnName("way");

                    b.Property<float?>("way_area")
                        .HasColumnType("real");

                    b.Property<string>("wetland")
                        .HasColumnType("text");

                    b.Property<string>("width")
                        .HasColumnType("text");

                    b.Property<string>("wood")
                        .HasColumnType("text");

                    b.Property<int?>("z_order")
                        .HasColumnType("integer");

                    b.HasIndex(new[] { "osm_id" }, "planet_osm_roads_osm_id_idx");

                    b.HasIndex(new[] { "way" }, "planet_osm_roads_way_idx");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "way" }, "planet_osm_roads_way_idx"), "gist");

                    b.ToTable("planet_osm_roads", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("GIsDataWorker.Models.planet_osm_way", b =>
                {
                    b.Property<long>("id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long[]>("nodes")
                        .IsRequired()
                        .HasColumnType("bigint[]")
                        .HasColumnName("nodes");

                    b.Property<string>("tags")
                        .HasColumnType("jsonb")
                        .HasColumnName("tags");

                    b.HasKey("id")
                        .HasName("planet_osm_ways_pkey");

                    b.ToTable("planet_osm_ways", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
